goldbergyoni/javascript-testing-best-practices

readme.md
Hi Yoni :)
I've changed the table of contents so clicking on the title will redirect directly to the section.
=> Make table of contents clickable

readme.korean.md, readme.kr.md
Hi, gold.
I want to say thank you first. Your repo is awesome!
So I want to let other Koreans see it as well, I just getting started to translate.
It is in progress.
=> Translate into Korean.

readme.md
=> fix bad link in 4.1

.all-contributorsrc
The bot will also need repository access (Need Yoni to do that)
https://allcontributors.org/docs/en/bot/installation
=> init allcontributors bot

.operations/questions-answers.md, readme-pt-br.md
=> Translations pt br staging

readme-pt-br.md
Translated section 4 to pt-br.
=> Translated section 4

readme.md
=> fixed typo in 1.4

readme.md
Felt free to fix a few things and align formatting.
=> style: fix typos and heading levels, improve punctuation, make formatting consistent

readme-pt-br.md
Finished translating sections 1, 2, 5, Team section and fixed some errors.
Also updated the PT-BR file according to the main file. (up to december 22th)
=> PT-BR translation

readme-pl.md, readme.md
Hi. First of all, really great project again! The Polish version is under-way [WIP] 🔥 Please, stay tuned. Best greetings
=> readme-pl.md

readme.md
Small fixes typo. Referring to issue [117](https://github.com/goldbergyoni/javascript-testing-best-practices/issues/117)
=> Fixed small typo

readme.md
I've spotted two spelling mistakes, which I've corrected
=> Correct two spelling issues

readme.md
#Hi!
I was going to start translating for pt-br, but I was notified in issue #149 this translation already exists.
I am simply adding the link to README.md and listing the contributors.
😃
=> Add link for pt-BR translation on README.md

readme-es.md
Just fixing a tiny mistake: the anchor links wasn't translate to Spanish and it wasn't work.
By the way, this is my first pull request ever in github, sorry if there is any mistake
=> fix(readme-es.md): anchors

readme-es.md
Just changed a small typo.
Awesome guide and translation! 👏
=> Spanish translation spellcheck

readme-es.md, readme-pl.md, readme-pt-br.md, readme-zh-CN.md, readme.kr.md, readme.md
First of all, sorry for not contributing with something that isn't really relevant, but if I was a beginner I'd probably have used data-testid instead of data-test-id. As I said, it's not relevant, but it's really helpful to learn the good way of bests practice :)
=> Updates data-testid attribute to data-test-id

readme-es.md
I did a few minor changes in the Spanish translation:
- update the number of bullets
- add portugue-br link
- update the 2.3 title (becouse of  761fe7a commit) 
- update the contributors
=> minor spanish changes

readme-pt-br.md
Adicionado espaço entre palavras no título da seção 5.3
=> Fix typo in portuguese version

readme.kr.md
- Remove unknown words
- Fix typo in code block
- Correct the wrong korean
=> Fix typo in README.kr.md

readme.md
Numeration fixes (added one & made other parts visible).
=> Numeration fixes
